### ISSUE TITLE
Does not compile for wasm32 target

### ISSUE THREAD

**Issue by vanarchist** [yjh0502/float_extras#1]
error[E0432]: unresolved imports `libc::c_double`, `libc::c_int`
 --> /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/float_extras-0.1.6/src/lib.rs:5:16
  |
5 |     use libc::{c_double, c_int};
  |                ^^^^^^^^  ^^^^^ no `c_int` in the root
  |                |
  |                no `c_double` in the root

error[E0432]: unresolved import `libc::c_int`
  --> /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/float_extras-0.1.6/src/lib.rs:38:9
   |
38 |     use libc::c_int;
   |         ^^^^^^^^^^^ no `c_int` in the root

**Comment by yjh0502** [comment]
Could you check if libm crate  has a math function that you need?
 - https://docs.rs/libm/0.1.3/libm/
 - https://github.com/rust-lang-nursery/libm

 `libm` crate is specifically for wasm32 target so I think it might meet your needs. Thanks!

**Comment by vanarchist** [comment]
Thanks for the recommendation. I'm actually trying to use your s2 crate which depends on float_extras. Would it be possible to use libm instead for s2? Should s2 be forked to make a version specifically for wasm32?

**Comment by yjh0502** [comment]
@vanarchist I updated `float_extras` on `rust-s2` to `libm`. Could you check if it works?
https://github.com/yjh0502/rust-s2/commit/f7a62d84febe239f217b57c1cb10c08e41a071ea

**Comment by vanarchist** [comment]
Thanks @yjh0502, it does build for wasm32 now. I'll be working with it more so I'll let you know if anything else comes up. I appreciate the quick turnaround on this.

**Comment by yjh0502** [comment]
`s2` `0.0.9` is just published, https://crates.io/crates/s2
